hash-format = "sha256"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b6e97c6bdac0e568015294cf58f0a9fa43fb70042d252db9b578dd85a0a99137"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "eb36ee82356acc82d716dd044172ca03fc0ffa3c002622eaab12cbfab6677e4c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d3b873718fd52fbc23823868871a1c2646f9a0e873bd4f0292076c62801119f5"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6e800080e9bc8efb8f1a94a6e4ed3167a58b3d8f29a4ae7aba8cdde35c08d13e"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
hash = "91238e01713f7198f62bd04b4f03654e353d59471ff52ca418bd1e2f65c6c702"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e612afec52bf64afc5792d2c65a35434a1bc8f3ab985b043a41c0493a00bd532"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "95b7ea759192f201a2c36bd286e9ed3d9b427aff086d3b23fa867922daa46559"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "73d9bbc111918af267e27ffc89c09e2bd63a106c571ecc08da3b3bb0c9948670"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "be17ce2e4cf969f67316e15151df21a04f3cbe16f0369b18d75b98c1bc846d7c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "afd2e9e3bf6bc4f50a54e2ef0c56cc585a46fd197b04828bbc9cc67dbea8d390"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "527441f56f12bd48d63de82dc5acec0a371fcaf4d2b21ec6975019b4dc79a5d3"
metafile = true
