hash-format = "sha256"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "d297f370d36b9afe3eed3cdabb48c919965ae61237a100d5a04ca17dcd9aa32c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f0886f508c636984a1fe09bbb7be2daafcbda8fe6e60f82b74a38299903e6927"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "dc2880322af594bc8d3d69f9859ba398b7f83aff47bfc9a828347d1535892cae"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fcf5aeb5a41fadabd7274196fed4a5e9e3a95cec5de9a3dfea889131576c4320"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "89804e03d79427fd428a669596a709b43433f07b4a46f3db8defb56fa4aa4fe2"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "24e4c0afdf00a05ea362f976a395aecd4b3a9f59acf505d51d8fbb3de2fb52f3"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "e9ac87726db4d37ee8f75c811791e115a581bc9ecc92f07ff8011385d45f87a2"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "c1906aafc5af2f95945d31f840263f3490efe781461fbcee33df3f3a68c431b3"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "c06d799c4d0abe75fec8713c790afe331ad04d837fda60a799c7bbf6857da537"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true
