name = "Overly Optimized"
author = "Cartrigger"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b6f21bdfed0ed633f3222258c5930a0c9b1b86eb433004a923ba983822ce449"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
