name = "OVOP"
author = "UTMG"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3644a5607d961b2ed6c77bde4e5b39792f44bc39eba27cc3afc0e3a4ef9e72b4"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.47"
